### ISSUE TITLE
ParsedLinesCount is increasing in each request

### ISSUE THREAD

**Issue by git-no** [Jisco/gedcom.json#28]
**Describe the bug**
The `ParsedLinesCount`value (number) has not the real value, it adds the current ParsedLinesCount to the previous, so it is duplicated by each loop using the parse function.
I created a webservice, API receiving the gedcom string and returning the json (see code below).

**Seems the bug is in file `parsing.ts`, var `stats` is not initialised in function `ParseText`.**
Did not tested ParseFile function.

**To Reproduce**

**Expected behavior**
Stats should be ragarding the current parsing run and not include previous parsing calls.

**Screenshots**
-

**Desktop (please complete the following information):**
 macOS, node 18, sveltekit 1.3.2, gedcom-json 1.0.6.

**Additional context**
```js
import { error } from '@sveltejs/kit';
import { JsonParsing, ParsingOptions } from 'gedcom.json';

/** @type {import('./$types').RequestHandler} */
export async function POST({ request }) {
	let json = {};
	try {
		const gedString = await request.text();

		// gedcom 
		const parsingOptions = new ParsingOptions();
		parsingOptions.SetText(gedString);
		parsingOptions.SetConfig(parserConfig);
		const parser = new JsonParsing(parsingOptions);
		const parsed = await parser.ParseTextAsync();

		json = { statistic: { parsed: parsed.Statistics.ParsedLinesCount, notParsed: parsed.Statistics.NotParsedLinesCount }, data: parsed.Object };
	} catch (err) {
		// @ts-ignore
		throw error(400, err.message);
	}

	if (!json) {
		throw error(400, 'No gedcom data exists.');
	}
	return new Response(JSON.stringify(json));
}
```

**Comment by Jisco** [comment]
Yes, thank you! 😃 
I reset the statistics now, please use version 1.0.8 an test again!
